; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[common]
firmware_version = '"1.2.0"'
platform = espressif8266 @ ^4.2.1
framework = arduino
lib_deps =
    teckel12/NewPing @ ^1.9.7
    arduino-libraries/NTPClient @ ^3.2.1
    mlesniew/PicoMQTT @ ^1.3.0
    tobiasschuerg/ESP8266 Influxdb @ ^3.13.2
    arcao/Syslog @ ^2.0.0
    jchristensen/Timezone @ ^1.2.6
    paulstoffregen/Time @ ^1.6.1
    yiannisbourkelis/Uptime Library @ ^1.0.0
build_flags =
    -std=c++11
build_src_filter = +<*> +<common/> +<sensor/> -<controller/>

;;Device Monitor
;;Usage: pio device monitor -e controller
build_type = debug
monitor_speed = 115200
monitor_filters = esp8266_exception_decoder, default


[env:sensor_src]
extends = common
board = esp01
board_build.ldscript = eagle.flash.8m6m.ld
extra_scripts =
    pre:include/common/settings/settings.py
    pre:include/sensor/settings/settings.py
lib_deps = ${common.lib_deps}
build_flags =
    ${common.build_flags}
    -DSRC_BARREL
    -D FIRMWARE_VERSION=${common.firmware_version}

upload_speed    = 230400
upload_protocol = esptool
upload_port     = COM3


[env:sensor_src_ota]
extends = env:sensor_src
upload_protocol = espota
upload_port     =rwssrcbar.local


[env:sensor_dst]
extends = common
board = esp01
board_build.ldscript = eagle.flash.8m6m.ld
extra_scripts =
    pre:include/common/settings/settings.py
    pre:include/sensor/settings/settings.py
lib_deps = ${common.lib_deps}
build_flags =
    ${common.build_flags}
    -DDST_BARREL
    -D FIRMWARE_VERSION=${common.firmware_version}

upload_speed    = 230400
upload_protocol = esptool
upload_port     = COM3


[env:sensor_dst_ota]
extends = env:sensor_dst
upload_protocol = espota
upload_port     = rwsdstbar.local


[env:controller]
extends = common
board = esp12e
extra_scripts =
    pre:include/common/settings/settings.py
    pre:include/controller/settings/settings.py
lib_deps =
    ${common.lib_deps}
    Wire
    adafruit/Adafruit BusIO @ ^1.17.4
    adafruit/Adafruit INA219 @^1.2.3
    mathertel/OneButton @^2.6.2
build_flags =
    ${common.build_flags}
    -D FIRMWARE_VERSION=${common.firmware_version}

upload_speed    = 460800
upload_protocol = esptool
upload_port     = COM9


[env:controller_ota]
extends = env:controller
upload_protocol = espota
upload_port     = rwscontro.local